### ISSUE TITLE
Float parameter parsing

### ISSUE THREAD

**Issue by ForNeVeR** [Pash-Project/Pash#205]
There is an error in the parameter parsing code. For example, I enter

    ping 8.8.8.8

In PowerShell this obviously works, but Pash throws an exception (it seems to me that it tries to parse `8.8.8.8` as float literal).

There are a couple of ignored tests in [`ShellExecutionTest` class](https://github.com/Pash-Project/Pash/blob/master/Source/TestHost/FileSystemTests/ShellExecutionTest.cs) because of this bug.

Stack trace:

```
ERROR: System.NotImplementedException: real_literal
   at Pash.ParserIntrinsics.AstBuilder.BuildLiteralAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1476
   at Pash.ParserIntrinsics.AstBuilder.BuildValueAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1320
   at Pash.ParserIntrinsics.AstBuilder.BuildPrimaryExpressionAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1021
   at Pash.ParserIntrinsics.AstBuilder.BuildCommandNameExprAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1679
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Pash.ParserIntrinsics.AstBuilder.BuildCommandArgumentAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1740
   at Pash.ParserIntrinsics.AstBuilder.BuildCommandElementAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1726
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Pash.ParserIntrinsics.AstBuilder.BuildCommandAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 1660
   at Pash.ParserIntrinsics.AstBuilder.BuildPipelineCommandAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 646
   at Pash.ParserIntrinsics.AstBuilder.BuildPipelineAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 560
   at Pash.ParserIntrinsics.AstBuilder.BuildStatementAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 207
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Pash.ParserIntrinsics.AstBuilder.BuildStatementListAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 146
   at Pash.ParserIntrinsics.AstBuilder.BuildScriptBlockBodyAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 136
   at Pash.ParserIntrinsics.AstBuilder.BuildScriptBlockAst(ParseTreeNode parseTreeNode) at \Pash\Source\System.Management\Pash\ParserIntrinsics\AstBuilder.cs:line 53
   at Pash.ParserIntrinsics.PowerShellGrammar.ParseInteractiveInput(String input) at \Pash\Source\System.Management\Pash\ParserIntrinsics\PowerShellGrammar.cs:line 316
   at Pash.Implementation.CommandManager.CreateCommandProcessor(Command command) at \Pash\Source\System.Management\Pash\Implementation\CommandManager.cs:line 101
   at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandManager commandFactory, Boolean addToHistory) at \Pash\Source\System.Management\Automation\Runspaces\Command.cs:line 80
   at Pash.Implementation.LocalPipeline.BuildPipelineProcessor(ExecutionContext context) at \Pash\Source\System.Management\Pash\Implementation\LocalPipeline.cs:line 187
   at Pash.Implementation.LocalPipeline.Invoke(IEnumerable input) at \Pash\Source\System.Management\Pash\Implementation\LocalPipeline.cs:line 174
   at System.Management.Automation.Runspaces.Pipeline.Invoke() at \Pash\Source\System.Management\Automation\Runspaces\Pipeline.cs:line 30
   at Pash.FullHost.executeHelper(String cmd, Object[] input, Collection`1& errors) at \Pash\Source\PashConsole\FullHost.cs:line 178
```

**Comment by ForNeVeR** [comment]
> E.g. `Write-Host 8.8.GetType()` will simply output `8.8.GetType()`.

I am sorry, but I cannot reproduce this with PowerShell 4. I got the following:

```
PS> write-host 8.8.GetType()
At line:1 char:24
+ write-host 8.8.GetType()
+                        ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
```

**Comment by ForNeVeR** [comment]
Ah, according to the latest publicly available 3.0 spec:

> •	An argument that is not an expression, but which contains arbitrary text without unescaped white space, is treated as though it were double quoted. Letter case is preserved.

But I still cannot see why something like `8.8.8.8` or `8.GetType` would not count as expression (and got preprocessed according to the above rule) but, for example, `$x.GetType()` or even `'abc'.GetType()` **is** an expression (and got executed instead).

**Comment by ForNeVeR** [comment]
Also there's the following text in the spec (I am talking about 8.2 here):

> •	Putting parentheses around an argument causes that expression to be evaluated with the result being passed instead of the text of the original expression.

So maybe "passing expression text instead of an evaluation result" should really be the default on some level? But it doesn't correspond with `Write-Host 'abc'.GetType()`, for example (here the expression gets evaluated). I'm totally confused :(

**Comment by ForNeVeR** [comment]
After playing with that a bit I've come to the following conclusion.

First of all, we need to parse "8.8.8.8" as PowerShell does: `(((8.8).8).8)` with two member access expressions. In that way we'll get rid of whitespace troubles mentioned by @sburnicki above.

After that, we may introduce a little hack to `AstBuilder.BuildCommandAst` so it will convert an expression to text if its root element is a `real_literal`.

**Comment by ForNeVeR** [comment]
@JayBazuzi, I think it's time to close this. Strange it wasn't closed automatically with my PR.
